#version: '3.8'
# see here https://docs.docker.com/compose/compose-file/compose-versioning/
version: '3.1'

services:

  be:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3001:80
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb+srv://%s:%s@uberapp.hvf8i.mongodb.net/uber?retryWrites=true&w=majority
      - DATABASE_TEST_URL=mongodb://localhost:27017/
    networks:
      - backend

  fe:
    stdin_open: true
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - 3000:80
    environment:
      - NODE_ENV=development
      - REACT_APP_BE_NETWORK=backend
      - REACT_APP_BE_PORT=5000
      - REACT_APP_SERVER_URL=${REACT_APP_SERVER_URL}
    depends_on:
      - be
    # specifies frontend and backend as the networks the fe service will have access to
    networks:
      - frontend
      - backend
      
# bridge networks to allow the containers to communicate with each other
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
